AllCops:
  Exclude:
    - ./features/step_definitions/*.rb
    - ./features/support/env.rb
    - ./features/support/helpers.rb
    - ./features/support/hooks.rb
Metrics/LineLength:
  Max: 200
MethodLength:
  Max: 60
Metrics/AbcSize:
  Enabled: false
BlockLength:
  Max: 100
Metrics/ClassLength:
  Max: 200
